[package]
edition = "2021"
name = "libsyncrpc"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytecheck = "0.6.12"
mmap-sync = "1.0.4"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"
rkyv = "0.7.45"
tempfile = "3.13.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
