[package]
name = "libsyncrpc-connection"
version = "0.0.0"
edition = "2021"

[dependencies]
tempfile = { version = "3.18.0", optional = true }
memmap2 = { version = "0.9.5", optional = true }

[features]
default = []
mmap = ["dep:memmap2", "dep:tempfile"]